# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Technoanarchist Revolution
tagline:          The Revolution Will Be Televisible
url:              http://reddit.com/r/technoanarchy/
paginate:         1
baseurl:          http://wholcomb.github.io/The_Technoanarchist_Revolution/
author:
  name:           Will Holcomb
  url:            http://dhappy.org
  email:          will@dhappy.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wholcomb/The_Technoanarchist_Revolution/
